package com.hzh.green.dao.sample.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hzh.green.dao.sample.model.entity.PersonInfoEntity;
import com.hzh.green.dao.sample.model.entity.PersonMobileEntity;
import com.hzh.green.dao.sample.model.entity.CertificateInfoEntity;

import com.hzh.green.dao.sample.db.PersonInfoEntityDao;
import com.hzh.green.dao.sample.db.PersonMobileEntityDao;
import com.hzh.green.dao.sample.db.CertificateInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personInfoEntityDaoConfig;
    private final DaoConfig personMobileEntityDaoConfig;
    private final DaoConfig certificateInfoEntityDaoConfig;

    private final PersonInfoEntityDao personInfoEntityDao;
    private final PersonMobileEntityDao personMobileEntityDao;
    private final CertificateInfoEntityDao certificateInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personInfoEntityDaoConfig = daoConfigMap.get(PersonInfoEntityDao.class).clone();
        personInfoEntityDaoConfig.initIdentityScope(type);

        personMobileEntityDaoConfig = daoConfigMap.get(PersonMobileEntityDao.class).clone();
        personMobileEntityDaoConfig.initIdentityScope(type);

        certificateInfoEntityDaoConfig = daoConfigMap.get(CertificateInfoEntityDao.class).clone();
        certificateInfoEntityDaoConfig.initIdentityScope(type);

        personInfoEntityDao = new PersonInfoEntityDao(personInfoEntityDaoConfig, this);
        personMobileEntityDao = new PersonMobileEntityDao(personMobileEntityDaoConfig, this);
        certificateInfoEntityDao = new CertificateInfoEntityDao(certificateInfoEntityDaoConfig, this);

        registerDao(PersonInfoEntity.class, personInfoEntityDao);
        registerDao(PersonMobileEntity.class, personMobileEntityDao);
        registerDao(CertificateInfoEntity.class, certificateInfoEntityDao);
    }
    
    public void clear() {
        personInfoEntityDaoConfig.clearIdentityScope();
        personMobileEntityDaoConfig.clearIdentityScope();
        certificateInfoEntityDaoConfig.clearIdentityScope();
    }

    public PersonInfoEntityDao getPersonInfoEntityDao() {
        return personInfoEntityDao;
    }

    public PersonMobileEntityDao getPersonMobileEntityDao() {
        return personMobileEntityDao;
    }

    public CertificateInfoEntityDao getCertificateInfoEntityDao() {
        return certificateInfoEntityDao;
    }

}
