package com.hzh.green.dao.sample.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hzh.green.dao.sample.model.entity.PersonInfoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "person_info".
*/
public class PersonInfoEntityDao extends AbstractDao<PersonInfoEntity, String> {

    public static final String TABLENAME = "person_info";

    /**
     * Properties of entity PersonInfoEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property CreateTime = new Property(1, java.util.Date.class, "createTime", false, "create_time");
        public final static Property UpdateTime = new Property(2, java.util.Date.class, "updateTime", false, "update_time");
        public final static Property DeleteFlag = new Property(3, Integer.class, "deleteFlag", false, "delete_flag");
        public final static Property Version = new Property(4, Integer.class, "version", false, "version");
        public final static Property PersonName = new Property(5, String.class, "personName", false, "person_name");
        public final static Property Sex = new Property(6, String.class, "sex", false, "sex");
        public final static Property Age = new Property(7, Integer.class, "age", false, "age");
    }


    public PersonInfoEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PersonInfoEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"person_info\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"create_time\" INTEGER NOT NULL ," + // 1: createTime
                "\"update_time\" INTEGER NOT NULL ," + // 2: updateTime
                "\"delete_flag\" INTEGER NOT NULL ," + // 3: deleteFlag
                "\"version\" INTEGER NOT NULL ," + // 4: version
                "\"person_name\" TEXT NOT NULL ," + // 5: personName
                "\"sex\" TEXT NOT NULL ," + // 6: sex
                "\"age\" INTEGER NOT NULL );"); // 7: age
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"person_info\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PersonInfoEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getCreateTime().getTime());
        stmt.bindLong(3, entity.getUpdateTime().getTime());
        stmt.bindLong(4, entity.getDeleteFlag());
        stmt.bindLong(5, entity.getVersion());
        stmt.bindString(6, entity.getPersonName());
        stmt.bindString(7, entity.getSex());
        stmt.bindLong(8, entity.getAge());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PersonInfoEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getCreateTime().getTime());
        stmt.bindLong(3, entity.getUpdateTime().getTime());
        stmt.bindLong(4, entity.getDeleteFlag());
        stmt.bindLong(5, entity.getVersion());
        stmt.bindString(6, entity.getPersonName());
        stmt.bindString(7, entity.getSex());
        stmt.bindLong(8, entity.getAge());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public PersonInfoEntity readEntity(Cursor cursor, int offset) {
        PersonInfoEntity entity = new PersonInfoEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // createTime
            new java.util.Date(cursor.getLong(offset + 2)), // updateTime
            cursor.getInt(offset + 3), // deleteFlag
            cursor.getInt(offset + 4), // version
            cursor.getString(offset + 5), // personName
            cursor.getString(offset + 6), // sex
            cursor.getInt(offset + 7) // age
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PersonInfoEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCreateTime(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setUpdateTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setDeleteFlag(cursor.getInt(offset + 3));
        entity.setVersion(cursor.getInt(offset + 4));
        entity.setPersonName(cursor.getString(offset + 5));
        entity.setSex(cursor.getString(offset + 6));
        entity.setAge(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(PersonInfoEntity entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(PersonInfoEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PersonInfoEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
